spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: dustpeo12# # mysql password
    username: root # mysql username
    url: jdbc:mysql://localhost:3306/thecp  #// ???, mysql schema name
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa